sudo: required
env:
  global:
  - secure: WahBXfSH77n6vw0zQdDB9j/auSIel9rBhZLQhU9DmIwxPCoOMYiln4nRUKpKeSvSe4S2DN89BuuXvbhvtOhNatdCKHDiU53asjxyJH5M+XLY0+yMuwu8/9/Zo0XaaRxwBqFgSoxR4nOfKEXZu1H5I9eV15uoBKIwU4XQKrcT9+ptBBD0z+nse2fQatep1NYKRslzw60xsQt1an3sN5hyVhSWqUhw0lCH/2D+3xqevEj76YBahLCoUHkc/JxCqu1IH9VoH9Tmy5BufPUxf0a+gg+4xf5FATlAM0Gs1Y2kF+BUSADeSq9BtaC0bgY2sAHs3YtqGA2IhUJXt1x33rLtQGayvUpPGrUCdKYbNlSO/itbyPasocZtsf1IlLfRIXXir1moiMiNvOMdUBdktLSNxzaOFNI4m/G57el8EEbF4+0EBjzBev53JqdX1HgDsNqbNbJRhVRrFU/7owigejaaMjvywP4ttyAeymvG9EVRyc9Vjx6EZMXoyO8+fM+xuyg88B4PG5n3vDq99ih/rfa4jZmgVjiNm/dhnMjfjvMMkDuUskgjirf0/9OdcRC8e4/oFxiQReal9QessGWKGaQ+Pi8sw0mhEj29sBPHxMv1gM546FBPKg4dRQdhU1A3Bz5YV0HK24IlmASTdBOgtxWJnqkPoX0Ak9MQlmHqaGU+h1A=
  - secure: B7MpDIZKPegbOnOMcxhRzIAjLWUh4z/jivzuOAXFtRy6IIOiawTFgFjL89koHnwY56kngcNORABzcnfdfIcY5A2gIvb/6mec/R+zq865z3Y8nHrxuYXp0Ej1H73XNxfhFhN5Xlb5mdEg7W9zP660wRFOG5tpZdXqJPdDYsGXyLVSuWbDOJDL7FUmrAeoGOrxAnaDXmVkjNmpUuJ1a7YsVoPHOqh4aKA/7PCh/AfvvO4xyMo0X8NDJV+YH4RZgRrtCtOptrA5z6X/Gk5lgNVOye9AFEKbxxkYQlJqohldoaW/+Y0MlEVXXrx/dj6L6aOZ7xaZOuoqhRoIuQ3n+t7/zmEhQpSlJpLTK9p5sFkEc5qIAwkDGU4O3ZNVwW7yJfSPBaOgUfXwHujdmjkQv7huvIFaQ2cAwSwEjqfLgVfTkkg6QmRTtQYju4FPxgzij47bGZlYzLCEf2zQ9p36Pa5K4dSGn5YIiDMNMH/Mc5yE+51jySLB48TtxkVQAYoOHrpFO7wlfK11C3D32n0CR/JvE9eRZTkr1/Mh7OUhetBNllKJ2PwPYAUx18vCENissEtw76GIMq88hy3GOnKrOXLDnLY1Xm918JFYI9o79ixAU8JHu7YbCu4bJ3QKHiU+J1CVq7RUv5154eoQ3Gcm99Ko43rLIkZGI32bMs0q4A7NAsI=
  - DOCKER_IMAGE_NAME=goruha/drupal-dev
services:
- docker
install:
- docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
script:
- docker build -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi && docker push $DOCKER_IMAGE_NAME
